### PR TITLE
Skill - ConcealedWeapon

### PR DESCRIPTION
**Pull request by JesterWizard**
The user can smuggle their equipped weapon into the arena.

(The uses they burn through don't carry back over though. More time needed to figure that out).

### CODE REVIEW

**Comment by MokhaLeee** [comment]
arena have its own logic on weapon selection. not here

**Comment by JesterWizard** [comment]
I'm not sure where else I could place it that makes sense. Looking at the arena `bmarena.c` looks likely. Specifically `ArenaGenerateBaseWeapons` but that doesn't exist in your skill system yet.

**Comment by MokhaLeee** [comment]
It just that function in vanilla determines the weapon. But obviously you need to do more work to find the proper weapon for your character, and then you need to modify the `ArenaBeginInternal` since `gArenaState.playerWpnType` have changed, then the whole function need to rewrite....

I don't think it is proper to introducing a massive overhaul to a small skill. So i think it is better not to merge such skill to community project.

**Comment by JesterWizard** [comment]
Welp, another one for the scrap heap I suppose....

**Comment by MokhaLeee** [comment]
https://feheroes.fandom.com/wiki/Template:Passives_Navbox

**Pull request closed without merging**
