### PR TITLE
Skill - Amische

### PR DESCRIPTION
**Pull request by JesterWizard**
Another gimmick skill, that prevents the user from using non-iron weapons. 

I'll just get out in front of this one and say: before you reject it consider that not all skills have to contribute to making characters roided death machines. There can be skills that help contribute to narrative as well. Ones that help flesh out certain characters by having certain personality traits (like religion) reflected in the gameplay.

### CODE REVIEW

**Comment by MokhaLeee** [comment]
> not all skills have to contribute to making characters roided death machines

Well I think you failed to understand the reason on rejection.

You need to think about two things.

1. Is there any deference on judging name string rather than name msg index?
2. Is there any deference on judging character index rather than character name msg index?
3. Should community project served for customized plot for specific story?

The reaspm why project is named as "kernel" is just because it should limit its functionality to meet the basic needs of the vast majority of users, this is also necessary to maintain code reliability. Yes ofcourse the game-designer what their game create more unique gameplay functionality, but that's just their own work rather than a feature need community project should support for.

**Comment by MokhaLeee** [comment]
> it should limit its functionality to meet the basic needs of the vast majority of users

And this is also the reason I think this PR should be rejected. If you feel that this feature is useful for your game plot, you should put it in your personal customized ROM instead of submitting it to the public repository.

**Comment by JesterWizard** [comment]
> Is there any difference on judging name string rather than name msg index?
1. Not sure, this was my first attempt at this. I'm sure you'll say "Then you should research it first" which is fine, but I don't see myself making another skill like this. 

>Is there any difference on judging character index rather than character name msg index?
2. Two or more characters could potentially have the same name if the hack creator so desires it.

> Should community project served for customized plot for specific story?
3. I feel it's about giving people options. Very few users are going to have the technical know-how to implement such skills themselves. So I didn't see a reason to limit ourselves in that department. 

>The reason why project is named as "kernel" is just because it should limit its functionality to meet the basic needs of the vast majority of users
Then I have learned something new : D

On a slighly different note, your standards for what contributes 'vast majority of users' are not clearly defined. I think this would be good to have in a contributor's note somewhere.

We're fast approaching the point where such gimmick skills will soon be the only ground we haven't touched. I'm more than happy to make a seperate branch for these and keep them away from your project, but it'd be nice to know in advance what's left in this list of skills that don't meet your standards. Otherwise I'm just wasting both our times. https://docs.google.com/spreadsheets/d/1zd99uevX953OZQiA_oJU9R3hqFao5mrW78wMHKPco-U/edit?gid=681794002#gid=681794002

**Comment by MokhaLeee** [comment]
Take pre-battle calc as an example, we left pad function at here: https://github.com/MokhaLeee/fe8u-cskillsys-kernel/blob/main/Wizardry/Core/BattleSys/data.event#L12

This allows gameplay designers to directly replace these functions to implement their own functionality. 

This also allows them to directly use the release as a **base rom** and do secondary customization.

**Pull request closed without merging**
