### PR TITLE
Skill - Death

### PR DESCRIPTION
**Pull request by JesterWizard**
Instantly skill the enemy if their name matches a specified string. 

As SKILL_EFF0 doesn't accept strings, I've had to put the string to check for inside the skill code block itself for now. 

Originally this was called 'DownWithArch' but I renamed it to be more generic.

### CODE REVIEW

**Comment by MokhaLeee** [comment]
I have to say that this skill doesn't make much sense... users can go to pre-battle to simply insert a slight function to determine the character's index and then all things have done...

**Comment by JesterWizard** [comment]
> I have to say that this skill doesn't make much sense... users can go to pre-battle to simply insert a slight function to determine the character's index and then all things have done...

It's a gimmick skill sure, but I think it's nice to have if only as a working example of using strings to accomplish something.

**Comment by MokhaLeee** [comment]
It is not reasonable to complicate a simple issue.

**Comment by JesterWizard** [comment]
Fine, I'll close it. 

For the record though, I don't agree. It's not complicated, just thinking outside the box.

**Pull request closed without merging**
