### PR TITLE
Skill - Shadowgift

### PR DESCRIPTION
**Pull request by JesterWizard**
Grants user the ability to use dark magic.

### CODE REVIEW

**Comment by MokhaLeee** [comment]
apparently it should not a function in pre-battle status and even not a battle-sys skill..... what's "pre-battle calc" mean?

**Comment by JesterWizard** [comment]
I guess I can just make it an chapter init skill? But then the user needs to start a new chapter if they gain the skill in the middle of the current chapter. My logic was if I make it pre-battle then it'll take effect immediately. 

Given that I could probably rewrite the logic to check the battle unit rather than make a `GetUnit` call. That way if the unit already has a dark magic rank I'm not wasting additional cycles. 

The community skill system seems to be use something called a `weapon usability calc loop` at hook point `0x16574`. The closest location I can I think of would be hooking inside `UnitHasMagicRank` in `bmunit.c`? Feel free to correct me if I'm wrong 😅

**Comment by MokhaLeee** [comment]
I prefer not to introduce such skill.
Making such a complex decision to achieve such a small feature will only lead to confusion.
On the other hand,  If you want to dynamically control the character's magic ability, why not directly give unit a magic weapon rank?

**Comment by JesterWizard** [comment]
In hindsight, I suppose if you remove the skill then the user can still use dark magic. So maybe it's not the best idea to have in skill form.

**Comment by MokhaLeee** [comment]
Yes, I think this PR could be closed directly

**Pull request closed without merging**
