### PR TITLE
Skill - Eclipse

### PR DESCRIPTION
**Pull request by JesterWizard**
Leave the enemy at 1HP if an attack would otherwise kill them (Skill % activation).

### CODE REVIEW

**Comment by MokhaLeee** [comment]
Your calculation method will cause the enemy's HP to be reduced to 1 regardless of whether the enemy is killed or not.

**Comment by JesterWizard** [comment]
I think I'll need a hint on this one, it's not 'very clear' to me. No matter where I put it in `BattleGenerateHit` it either doesn't activate, or displays the skill animation for the wrong side. You'd think sticking it in the `else` part of `if (defender->unit.curHP == 0)` would do the trick but nope.

**Comment by MokhaLeee** [comment]
There has already a skill named "SID_Bane" played the seem effect as this PR

**Comment by MokhaLeee** [comment]
Oh I find that the skill name is not consistant to it's effect:

`bane` should directly leave unit to one hp: https://fireemblem.fandom.com/wiki/Bane
`Mercy` should leave unit as 1 hp if killing: https://fireemblem.fandom.com/wiki/Mercy
`Eclipse` should neutralize the enemy unit's defenses https://fireemblem.fandom.com/wiki/Eclipse_(Skill)

**Comment by MokhaLeee** [comment]
https://github.com/MokhaLeee/fe8u-cskillsys-kernel/commit/32ab0837b4a97a503f3c1bec0c5ff99569dd94cc

**Comment by JesterWizard** [comment]
> Oh I find that the skill name is not consistant to it's effect:
> 
> `bane` should directly leave unit to one hp: https://fireemblem.fandom.com/wiki/Bane
> `Mercy` should leave unit as 1 hp if killing: https://fireemblem.fandom.com/wiki/Mercy
> `Eclipse` should neutralize the enemy unit's defenses https://fireemblem.fandom.com/wiki/Eclipse_(Skill)
> 
> The skill name, skill icon and the skill effect are incompatible in this PR, and the effect has been achieved by skill Mercy and the icon has been used by `SID_Luna` and `SID_LunaAttack`

No the Eclipse skill in the ASM skill system is meant to function in the reverse order of Bane. It should only reduce your opponent's HP to 1 if you wouldn't otherwise kill them. 

Though if you don't care for it I'll close this PR. Because the Tellius version is straight up broken and I have no intention of adding that.

**Comment by MokhaLeee** [comment]
Sure

> No the Eclipse skill in the ASM skill system is meant to function in the reverse order of Bane.

I think this is an obvious naming error on community project. In either version of the original game, `Eclipse ` always has a similar mechanic to the `Luna` rather than `Mercy`

**Comment by JesterWizard** [comment]
Sure no worries. I'll change the name to something else when I get time.

**Comment by JesterWizard** [comment]
I'm closing this for now.

**Pull request closed without merging**
