### PR TITLE
Skills - Push Skills

### PR DESCRIPTION
**Pull request by JesterWizard**
All of the push skills (boost stat by +5 when HP is full).

Strength, Magic, Defense, Resistance, Luck, Skill, Speed, Spectrum (and Movement).

### CODE REVIEW

**Comment by MokhaLeee** [comment]
this can judge hp just at one time

**Comment by JesterWizard** [comment]
I'm not sure what you mean? Are you saying that the HP check is made only ever once? Because I tested changing Eirika's HP between turns and the bonuses reapplied when I restored her to max health.

**Comment by JesterWizard** [comment]
So thing like what I've highlighted below at the beginning of each stat getter function for the skills `DefGetterSkills` etc?

Store the values for current and max HP for the unit in advance so the getter functions aren't called for every skill?

image

**Comment by MokhaLeee** [comment]
Fine, I may modify on it by myself later

**Comment by MokhaLeee** [comment]
https://github.com/MokhaLeee/fe8u-cskillsys-kernel/pull/98

**Pull request merged**
