### PR TITLE
Skill - Dazzle

### PR DESCRIPTION
**Pull request by JesterWizard**
Enemies cannot counterattack this unit. 

SIDE NOTE:
I had to put the skill in both `PreBattleCalc.c` (to set the counter bit that makes the enemy's stats be set as `--` in battle) and in `BattleOrder.c` to actually stop them from counterattacking.

Although, I wasn't able to get the forecast menu to display that they cannot counterattack for some reason.

### CODE REVIEW

**Comment by MokhaLeee** [comment]
apparently this skill should take effect in battle-weapon

**Comment by JesterWizard** [comment]
I've set `bu->canCounter = false` there in `SetBattleUnitWeaponVanilla` but that doesn't seem to do what's required. It just sets the enemy's stats to `--` in battle. It doesn't actually stop them from counterattacking. 

What I really need is the code that checks if a weapon has the `uncounterable` property set, but that doesn't seem to be in this skill system yet. And maybe some way to fudge the range check, so the enemy's stats show they can't counterattack in the forecast menu?

That's what comes to mind anyway. You might know a simplier way to do it.

**Comment by MokhaLeee** [comment]
weapon can counter is used mainly for judgement whether target need to update weapon usage in Battle2Unit routine, youshould directly remove the weapon, just like what vanilla did

**Comment by MokhaLeee** [comment]
spend more time on reading decomp code rather than purely random testing, which may just lead to a large number of low-reliability codes that cannot cover all cases.

**Pull request merged**
