### PR TITLE
Skill - DivinePulse

### PR DESCRIPTION
**Pull request by JesterWizard**
A 30% + Skill chance to turn a missed attack into a hit. 

Figured it was about time we added some more Engage skills.

Would be nice if we could replicate the Three Houses verson of this too, but I'm not sure if the GBA will allow it.

### CODE REVIEW

**Comment by MokhaLeee** [comment]
Apart from the appearance of animation, I don't see any other meanings of this function?

**Comment by JesterWizard** [comment]
`gBattleHitIterator->attributes |= BATTLE_HIT_ATTR_MISS` is used to determine if an attack has hit or missed and is set after the 2RN check has failed. In this case, if that happens, one of two things will occur. 

- If the `DivinePulse` is defined, then a 1RN check will be executed (based on a 30% + skill % chance) to avoid setting `gBattleHitIterator->attributes |= BATTLE_HIT_ATTR_MISS`  (essentially turning the missed attack into a hit). If this check fails, then the attack misses. 

- If `DivinePulse` isn't defined, then we just proceed as usual with `#else` where a missed attack sets `gBattleHitIterator->attributes |= BATTLE_HIT_ATTR_MISS`.

**Comment by MokhaLeee** [comment]
seems that this should check on lck rather than skl

https://fireemblem.fandom.com/wiki/Divine_Pulse

**Comment by JesterWizard** [comment]
So it should, fair enough. Luck makes more sense thematically anyway.

**Comment by JesterWizard** [comment]
"Chance increases with high luck" doesn't exactly state how luck affects the proc rate. I feel my initial explanation was better.

**Comment by MokhaLeee** [comment]
yeah, I also think this explanation is strange. But that this vanilla

**Comment by JesterWizard** [comment]
Maybe so, but there's no reason to stick to it if a better definition can be provided.

On the subject of vanilla, FE8 has multiple well known glitches. Following your logic, does that mean we shouldn't remedy them because it is default behaviour?

**Comment by MokhaLeee** [comment]
Your point is reasonable. Although I'd prefer to follow to the original if there are no obvious suitable reasons, but it makes sense to make the necessary changes if it's obvious that there is a need for optimization.

**Comment by JesterWizard** [comment]
I can respect that. I personally wouldn't suggest a change to wording if the original implementation makes sense. Only in cases where definitions can be ambiguous.

**Pull request merged**
