### PR TITLE
Skill - Petrify

### PR DESCRIPTION
**Pull request by JesterWizard**
Apply the stone status to the enem unit (Skill % activation).

### CODE REVIEW

**Comment by MokhaLeee** [comment]
Find on how other parts of the kernel code give debuff status and then modify this PR again.

**Comment by JesterWizard** [comment]
I'm not seeing the problem. If it's because I didn't use ` defender->statusOut` that's because it straight up doesn't work. I need to write the status back to the unit struct for it to persist and I'm guessing ` defender->statusOut` doesn't. 

If it's something else I'm all ears.

**Comment by MokhaLeee** [comment]
see
https://github.com/FireEmblemUniverse/fireemblem8u/blob/master/src/bmbattle.c#L1131
https://github.com/FireEmblemUniverse/fireemblem8u/blob/master/src/bmbattle.c#L1199

**Comment by JesterWizard** [comment]
Can't get it to work any other way. I'll just close.

**Pull request closed without merging**
