### PR TITLE
Skill - CriticalOverload

### PR DESCRIPTION
**Pull request by JesterWizard**
Gain +1 crit for every 3 points the skill holder is over 100 for their hit rate.

### CODE REVIEW

**Comment by MokhaLeee** [comment]
put them in switch block

**Comment by JesterWizard** [comment]
Please elaborate, do you mean the ``PreBattleCalc.c`` file? My argument against putting it in there is that it won't take account of the enemy's avoid rate (by default) as well as the myriad of other skills that can affect hit rate beforehand.

**Comment by MokhaLeee** [comment]
because battle status should be modified after initialization. At that time hit rate hold the possibility not to be initialized yet.

**Comment by JesterWizard** [comment]
I still don't see a reason to move it. ``FlashingBlade`` in ``BattleCalcReal.c`` also modifies crit rate after calculating anything in ``PreBattleCalc.c`` that might modify the two units' battle speeds. This skill operates under the same principle, but substituting battle speed for hit rate.

**Comment by MokhaLeee** [comment]
I think you can try to figure out another qestion and then you may realize the points,

what if another developer want to make unit gain 1 battle hit rate when they hold every 3 percent battle critical rate above 100%？

**Comment by JesterWizard** [comment]
Well, yeah in that case it wouldn't work since the effective hit rate is calculated in advance of the effective crit rate, so you'd be stuck with a reduced 100% hit rate to work with. I suppose when thought of in the context of the reverse, it makes some sense to have them together at the end of pre-calc (even if both hit rate and crit rate can be edited after these skills run). 

Fine, I'll move it. 

The hypothetical is assuming though, because what are the chances of anyone else adding skills at this point? : D

Maybe if we see an uptick in adoption.

**Comment by MokhaLeee** [comment]
yeah, it depends on users' amout

**Pull request merged**
