### PR TITLE
Skill - AngerPoint

### PR DESCRIPTION
**Pull request by JesterWizard**
If the unit has sustained a critical hit this turn, then +10 ATK for the rest of the turn.

### CODE REVIEW

**Comment by MokhaLeee** [comment]
it is meaningless toodify unit status rather than battle status. also mind on code style

**Comment by JesterWizard** [comment]
Not necessarily, the boost is kept on the player turn. Which is what I want.

**Comment by MokhaLeee** [comment]
battle flags is designed to be cleared at start of each battle

**Comment by JesterWizard** [comment]
Then the skill is useless if I can't make the boost persist. I'll think about it more later...

**Comment by JesterWizard** [comment]
What I think I need are flags that reset on a turn change

**Comment by JesterWizard** [comment]
I'm gonna close this. I've lost interest in it.

**Pull request closed without merging**
