### PR TITLE
Skill - Nonconforming

### PR DESCRIPTION
**Pull request by JesterWizard**
Invert the effects of the weapon triangle for both skill holder and enemy in battle.

### CODE REVIEW

**Comment by MokhaLeee** [comment]
Multiplication is a great performance overhead.

**Comment by JesterWizard** [comment]
Is the performance penalty really that egregious? 

My next idea then would be to use a boolean and a tertiary operator to decide whether to evaluate the triangle boost to normal or inverted. But then how do you handle stacking it with another skill that doubles the boost without incurring a performance penalty? Bitwise operations?

**Comment by MokhaLeee** [comment]
Obviously a large number of `MUL` instructions will affect performance, especially when it exists in performance sensitive battle-calc routine. I think there is a way to avoid so many `MUL` instructions. If there is no way to reduce such amount of `MUL`, I tend not to introduce such functionality.

**Comment by MokhaLeee** [comment]
But actually the current performance of this part of the code is really worrying. Later on this part of code need to remaking. Since this PR does not provide icons, I can directly introduce the skill effects into it. I think we may close this PR first.

**Comment by JesterWizard** [comment]
I noticed the weapon triangle boosts seem to be twice as strong as vanilla. +/- 30 hit and +/- 2 damage?

image
image

**Comment by MokhaLeee** [comment]
yes

**Comment by JesterWizard** [comment]
Is that not the sort of thing that should be a toggleable option rather than default?

+/- 30 hit is immense in a game not balanced around it.

**Comment by MokhaLeee** [comment]
Just as comment, that value is just used for UI

**Comment by JesterWizard** [comment]
What are we doing with this skill? You mentioned earlier how the performance of the weapon triangle code itself was concerning you. I substituted out the `mul` instructions, so the skill itself should be much more performant. 

Will it remain open then until you've had a chance to rewrite the weapon triangle code?

**Comment by MokhaLeee** [comment]
The WTA code will be reworked in the future, but for now it can be integrated to implement the function.

**Pull request merged**
