### PR TITLE
Skill-Miracle

### PR DESCRIPTION
**Pull request by JesterWizard**
Survive a lethal hit if the skill holder has more than 1 HP.
(Skill % activation).

### CODE REVIEW

**Comment by MokhaLeee** [comment]
oh well, inori skill has played the same role as this skill

**Comment by MokhaLeee** [comment]
祈り

**Comment by JesterWizard** [comment]
Damn. Closing then

**Comment by MokhaLeee** [comment]
BTW，I think maybe this skill can set such as "survive under critial attack"

**Comment by JesterWizard** [comment]
That seems very niche.

Might be a cool idea if we run out of skills to add.

**Pull request closed without merging**
