### PR TITLE
Skill - LastWord

### PR DESCRIPTION
**Pull request by JesterWizard**
If the enemy doubles, the skill holder also doubles.

I used the enum BATTLE_FOLLOWUP_SPEED_THRESHOLD this time.

### CODE REVIEW

**Comment by MokhaLeee** [comment]
I think you failed to understand what I mean.

> Obviously, purely judging the speed difference **cannot cover all situations**. Since there is no particularly good way to deal with it, my opinion on this skill is rejection

**Comment by JesterWizard** [comment]
By that logic, pretty much all of the `fighter` skills should have been rejected as well. So no, I'm not sure I do understand. If there's some edge case that means this skill wouldn't behave as expected, then surely it applies to all of them as well?

**Comment by MokhaLeee** [comment]
Current skills are facing a **deadlock** problem. and I don't see fighter related skills have any bugs?

**Comment by JesterWizard** [comment]
> Current skills are facing a deadlock problem. and I don't see fighter related skills have any bugs?

All fighter related skills in `BattleHit.c` are using this calculation to determine whether they should apply to the unit: `basic_judgement = (actor->battleSpeed - target->battleSpeed) >= BATTLE_FOLLOWUP_SPEED_THRESHOLD;`. The only thing `LastWord` does differently is reverse the actor and target positions `(arget->battleSpeed - actor->battleSpeed) >= BATTLE_FOLLOWUP_SPEED_THRESHOLD`. 

So what use case does this implementation fail that doesn't also apply to the fighter skills? I don't mean to come off argumentative, I just don't see what's different?

**Comment by MokhaLeee** [comment]
whether the lastword take effect is dependent on fighter skills judgement on both sides

**Comment by JesterWizard** [comment]
Okay so the execution is a little muddled and undefined because of how different fighter skills can interact with each other on different units. I still don't see how this is exclusive to LastWord though.

But fine, just leave this skill for now then I guess.

**Comment by MokhaLeee** [comment]
because this skill need to judge another side battle can double to decide itself can double. But during another side can-double judgement, it will also do the same thing.....

**Comment by JesterWizard** [comment]
Shall I just remove the skill effect and have you merge the info for now? For this and BlackMagic. 

No point leaving them sit here.

**Comment by MokhaLeee** [comment]
okay

**Comment by JesterWizard** [comment]
Good to go here.

**Pull request merged**
