### PR TITLE
Skill - LiquidOoze

### PR DESCRIPTION
**Pull request by JesterWizard**
If a unit would attempt to steal HP from a unit with this skill, they lose as much instead. 

However, they cannot fall below 1 HP.

### CODE REVIEW

**Comment by MokhaLeee** [comment]
1. can they properly cooperate with devil related skills

2. can they work properly with nosferatu banim

**Comment by JesterWizard** [comment]
1. Will have to look into this later to be sure. 

2. I hacked Nosferatu onto Vigarde as the debug chapter doesn't have any magic units, so I didn't see the magic animation play. But it did correctly drain HP from the attacking unit on the map animation.

I think I can make this cleaner anyway. I'll get to it when I get time.

**Comment by JesterWizard** [comment]
After hours of investigation I'm honestly pretty stumped. It surprises me how hard it is to handle both the HPSTEAL and DEVIL effects simultaneously. I keep running into an issue where the LiquidOoze skill holder's HP keeps increasing past the cap (presumably up to the 255 limit on the byte value) before switching to the Nosferatu user (who's HP does correctly decrease).

**Comment by MokhaLeee** [comment]
I think this skill effect has done on testing?

**Comment by JesterWizard** [comment]
Not sure what that means?

**Comment by MokhaLeee** [comment]
well I this this skill may be eable to be merged?

**Comment by JesterWizard** [comment]
Oh okay, so do I just remove the skill effect and let you handle it?

**Comment by MokhaLeee** [comment]
I think this PR has been fine till merge?

**Comment by MokhaLeee** [comment]
well the skill effect failed to deal damage on defender when it is activated.

**Comment by JesterWizard** [comment]
That isn't the case. The defender (Nosferatu user) does indeed take damage. As you can see in this video. 

The attacker (LiquidOoze skillholder) also takes damage as well. I can work around that by making the skill check for LiquidOoze just before damage is dealt to the attacker, but I still have the issue with the increasing HP bar I can't solve. 

Honestly all I could think to do was forcibly disable battle animations for the skill, so if you can think of something else it's all yours. 


https://github.com/user-attachments/assets/88769f71-5878-4a06-ac53-06b052876f2d

**Comment by MokhaLeee** [comment]
If attacker does not use Nosferatu but a simple hp-drain (which has been change to devil), attacker may not cause damage to defender. Well their still have other problems. I think you can pull the skill info first

**Pull request merged**
