### PR TITLE
Skill - Lifetaker

### PR DESCRIPTION
**Pull request by JesterWizard**
Heal 25% of the skill holder's max HP on killing an enemy. 

I tried to use the HP healing animation which I think is `BeginUnitHealAnim` but I got an error about implicit declarations. So I had to use `StartStatusHealEffect` instead.

### CODE REVIEW

**Comment by MokhaLeee** [comment]
The functionality is not quite dealt particularly well. I have submit a better method on post-action heal as: https://github.com/MokhaLeee/fe8u-cskillsys-kernel/commit/a2eee758d1d94a217567fec2f2e344647f09d942

You can add skill info etc based on this commit.

**Comment by JesterWizard** [comment]
Almost perfect now. Just one slight issue. 

When the unit's health bar displays just before the healing animation starts, It#s already 25% ahead of where it should be.

So if Eirika had 9/32HP and started healing, it'll show 17/32HP on her health bar and heal up from there but correctly display 17/32HP afterwards

**Comment by MokhaLeee** [comment]
it is recommended to repull a new PR by just modify on latest commit of main branch

**Comment by MokhaLeee** [comment]
> It's already 25% ahead of where it should be.

I may fix it after merging your new PR

**Pull request merged**
