### PR TITLE
Skill - Gamble

### PR DESCRIPTION
**Pull request by JesterWizard**
Skill information for Gamble. 

Skill effect: Halved hit but doubled crit. 

I gave it my best shot but I couldn't get it working. This is all the skill information for now.

### CODE REVIEW

**Comment by MokhaLeee** [comment]
rejected since community project should not merge unreliable experimental code.

If you are interested in such menu operation, I think you can test on your own demo

**Comment by MokhaLeee** [comment]
https://github.com/MokhaLeee/fe8u-cskillsys-kernel/pull/227

**Comment by JesterWizard** [comment]
What? You asked me to provide the skill info for a unit menu skill and so I did. The actual code of the operation has been commented out.

**Comment by MokhaLeee** [comment]
directly remove the menu ops functions

**Pull request merged**
