### PR TITLE
Skill - NoGuard

### PR DESCRIPTION
**Pull request by JesterWizard**
Both sides have a 100% hit rate.

### CODE REVIEW

**Comment by MokhaLeee** [comment]
This effect should not be in pre-battle but in battle-calc real

**Comment by JesterWizard** [comment]
> This effect should not be in pre-battle but in battle-calc real

But it is though?

image

**Comment by MokhaLeee** [comment]
Incorrect calculation methods will lead to reduced code quality and introduce potential bugs in the development of future new features.

**Comment by MokhaLeee** [comment]
This calc should be set after `ComputeBattleUnitEffectiveHitRate`

**Comment by JesterWizard** [comment]
> This calc should be set after ComputeBattleUnitEffectiveHitRate

`ComputeBattleUnitEffectiveHitRate` **is** in `PreBattleCalc.c` which is the opposite of where you told me to put `NoGuard`. On that note, I have my reservations about this change, as now when the defender attacks the skill holder, the adjusted hit rate is not reflected for the defender on the battle screen (but it is in the forecast oddly enough).

image


> Incorrect calculation methods will lead to reduced code quality and introduce potential bugs in the development of future new features.

Regarding this, I can't set the defender's hit rate to 100% as it's a prebattle skill, so changes to the defender will get overwritten. So in order to circumvent that, I need to reduce the attacker's avoid to some abritrary negative value to account for if they don't have enough 'positive' avoid to make the defender's hit rate 100%. If you can suggest a cleaner way of doing it, I'm open to suggestions.

**Comment by MokhaLeee** [comment]
Read on vanilla battle-calc(https://github.com/FireEmblemUniverse/fireemblem8u/blob/master/src/bmbattle.c#L183C6-L183C20) to get the idea:

put the calculation in `ComputeBattleUnitEffectiveStats`(battle-calc real), which lies after `ComputeBattleUnitStats`(pre-battle calc)

> ComputeBattleUnitEffectiveHitRate is in PreBattleCalc.c

fixed https://github.com/MokhaLeee/fe8u-cskillsys-kernel/commit/b13691e906e4bbfffe8da97db9a5061c63778979

**Pull request closed without merging**
