### PR TITLE
Skill - ConcealedWeapon

### PR DESCRIPTION
**Pull request by JesterWizard**
Now that you've shown me how easy it is to add in new files for more unique skills, I figured I'd take another crack at this one. 

Skill effect: Smuggle in the unit's equipped weapon into the arena.

### CODE REVIEW

**Comment by MokhaLeee** [comment]
As we have discussed before, Arena weapons should not just hacked here.

**Comment by JesterWizard** [comment]
On the subject of lyn jumps, I can't generate them. I've been getting around this by commenting out those lines in the make file. I'll look into seeing if there's a fix for it, because it's starting to becomes a hassle honestly.

I think I'm just going to keep it as a seperate skill for myself. It works, it doesn't cause any weird glitches to other users' stats or inventories and doesn't activate for othe units that don't have it. If I figure out a solution for the protector/detector lyn stuff, and it still works I'd call that a success.

**Comment by MokhaLeee** [comment]
I guess it will cause bug if a character with a bow-skilled job use a sword to enter the arena, then he may be encountered an archer

**Comment by JesterWizard** [comment]
Actually I'll need to test that one. Bow users might not be able to attack at all

**Comment by JesterWizard** [comment]
I've just realized that despite all my checks, this doesn't account for magic. 

This is on hold for now. You're clearly thinking further ahead than I am.

**Comment by JesterWizard** [comment]
Okay it finally works. 

I calculate and compare the min and max ranges of the opponent's arena weapon and the skill holder's equipped weapon to see if the opponent can retaliate. If not the skill doesn't activate. This also accounts for custom ranges such as an enemy having a 2-4 range weapon and the user could have a 3-5 range weapon equipped. 

After that, the user's weapon is changed and a final check is performed on the range of the arena field by checking if both combatants don't have bows and resetting the range of the field to 1 if they don't. This ensures that both combatants can fight (as the enemy might have a lightning, and the player might have previously had a bow, but then switched to a melee weapon).

It's a bit complex, but it covers every combination of weapon types in the arena as well as their ranges.

**Comment by MokhaLeee** [comment]
The question raised before is only one aspect. The current modification only circumvents the problem, but does not solve it.

A simple question is, why do enemies with bows appear? This modification does not answer this fundamental question. Similarly, it tolerates potential bugs caused by insufficient modifications. For example, the vanilla will try to balance the combat power of both sides. Obviously, the current modification will cause some unbelievable unbalanced battles in the arena.

Sure, this doesn't mean that the current modifications are unusable. However, I think these changes are not suitable for merging into the community project because they do not strictly adhere to the original program's execution logic. This could introduce potential bugs and cause issues for other developers.

Also, the lynjump detection will report error. You need to refer to my previous submission and provide corresponding protection measures for lynjump's functions to prevent possible failures caused by function renaming when C-LIB is modified in the future.

**Comment by JesterWizard** [comment]
I'm closing this, and keeping it to my fork.

**Pull request closed without merging**
