### PR TITLE
Skill - VengefulFighter

### PR DESCRIPTION
**Pull request by JesterWizard**
When defending, this unit always doubles.

### CODE REVIEW

**Comment by MokhaLeee** [comment]
For now, battle order related skill effect may not merged since the efxskill anim order at each tound is hardcoded. Maybe later we need a discussion on this.

**Comment by JesterWizard** [comment]
Shall I just close this if you're not accepting round based skills right now?

**Comment by MokhaLeee** [comment]
Yeah

**Comment by MokhaLeee** [comment]
https://github.com/MokhaLeee/fe8u-cskillsys-kernel/commit/60b2a3c3afb064f467ebff837f31253c45776d05

**Pull request closed without merging**
