### PR TITLE
Added Forager

### PR DESCRIPTION
**Pull request by AliScrooge**
Skill - Forager

Recover 20% HP each turn if on a Plain, Forest or Mountain.

Technically add an unnecessary call to gBmMapTerrain since that information is also accessed in MakeTerrainHealTargetList, but I belive that maintaining consistent location for new skill is more important than such minuscule optimisation

### CODE REVIEW

**Comment by MokhaLeee** [comment]
reviewed with comments in file

**Comment by AliScrooge** [comment]
Are you referring to the added comment in the file ? If so, I will get them out. I added them out of a desire to not simply drop the id number without precising wich id corresponded to wich tile

**Comment by MokhaLeee** [comment]
I mean you can directly enable your skill rather than comment it out in skills.enum.txt. Directly give it a definition, then kernel may automatically give it a enum.
```
~//~ SID_Forager
```

**Comment by MokhaLeee** [comment]
> especially once we pass the 255 skill treshold

That's doesn't matter, `#if defined(SID_Forager) && (SID_Forager < MAX_SKILL_NUM)` may handle on overflow issue to directly not compile them.

**Comment by MokhaLeee** [comment]
This PR will be merged and solved the issue by myself, next time mind the code style

**Comment by MokhaLeee** [comment]
https://github.com/MokhaLeee/fe8u-cskillsys-kernel/commit/75b07bf81ffbcc48b362cfd9d3a6bae2f9247fae

**Pull request merged**
